# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager:
# Aliases allow you to create nicknames for gh commands
aliases:
    co: pr checkout
    newpr: |
        !set -e
        TEMPLATE_FILE=$(mktemp)
        BRANCH=$(git rev-parse --abbrev-ref HEAD)
        PR_TEMPLATE_PATH="$PWD/.github/PULL_REQUEST_TEMPLATE.md"

        if echo "$BRANCH" | grep -q '[0-9]'; then
          AWK='{print $1 "-" $2}'
        else
          AWK='{print $1 "-ðŸ…"}'
        fi

        SHORT_NAME=$(echo "$BRANCH" | tr '[:lower:]' '[:upper:]' | awk -F'-' "$AWK")

        echo "[$SHORT_NAME]" > "$TEMPLATE_FILE"

        if [ -f "$PR_TEMPLATE_PATH" ]; then
          cat "$PR_TEMPLATE_PATH" | tail -n +2 >> "$TEMPLATE_FILE"
        fi

        "$EDITOR" "$TEMPLATE_FILE"
        BODY="$(cat $TEMPLATE_FILE)"
        TITLE="[$SHORT_NAME] $1"

        gh pr create -a @me -d --title "$TITLE" --body "$BODY"
# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:
# What web browser gh should use when opening URLs. If blank, will refer to environment.
browser:
version: "1"
